TITLE='A paired evaluation framework for policy selection in sequential perturbation screening'
ABSTRACT='''Sequential perturbation screens are often evaluated by reporting the strongest policy in a comparison, although this score combines screening utility with gains introduced by policy selection. We present a paired evaluation framework that separates these contributions by following the same selected interventions across discovery and replication readouts. The framework specifies the selection rule, available policy set, acquisition budget and unit of uncertainty. Across three public single-cell perturbation studies, eight numerical policies and 3,600 matched runs, an exploratory expansion from one to seven available policies increased discovery hit rates more than replication hit rates by 5.98, 1.58 and 4.81 percentage points. An exact decomposition relates this contrast to changes in policy-selection weights and cross-readout differences. Analyses of selection scope, task heterogeneity, policy omission and response endpoints identify when gains transfer, including a reversal under continuous scoring in one study. These results motivate a reporting protocol for sequential screening that distinguishes a fixed policy from a retrospectively selected winner, accounts for the cost of policy comparison and evaluates selected interventions on a separate readout. The framework provides an operational basis for assessing screening efficiency without conflating discovery-side selection gains with transferable utility.'''
INTRO_ADDITIONS='''In a sequential screen, performance depends on decisions made before and during data acquisition. A policy maps the current observation history to the next batch of interventions. A benchmark then makes a further decision when it chooses which completed policy run to report. These operations have different information requirements: the acquisition policy can use only responses already observed, whereas the benchmark can compare the terminal outcomes of several trajectories. Treating the second operation as if it were part of a single prospective trajectory can misattribute the benefit of comparison to the policy itself. The relevant evaluation target is therefore the complete procedure that produces the reported intervention set.

This issue is related to, but distinct from, leakage of evaluation data into model development. Here, policy-selection leakage denotes the reuse of benchmark outcomes to choose a reported policy while presenting those same outcomes as an independent assessment of its performance. No direct access to a replication readout is needed for discovery-side selection optimism to occur. Conversely, a discovery-to-replication difference does not by itself establish leakage: the measurements may differ in noise, perturbation efficacy or biological context. A useful evaluation must specify what information selected the winner and then measure what fraction of its advantage persists elsewhere. General concerns about adaptive model evaluation motivate this separation, but do not determine the sign or magnitude of the contrast in a perturbation screen [22,23].

Public perturbation archives allow this question to be examined without conducting a new experimental screen. Candidate identities can be aligned across archived measurements, and acquisition can be replayed while withholding one readout from the policy. Such replay preserves a common intervention set for evaluation, avoiding a comparison in which each readout is scored on a different collection of genes. It also makes the initial pool, budget and complete policy history available for inspection. Its inferential target is the behaviour of an explicitly specified screening procedure on the archive; the biological meaning of the second readout depends on how the source study generated it.'''
INTRO_END='''We introduce a paired evaluation framework for sequential perturbation screening and use it to characterize the contribution of retrospective policy selection. The analysis follows eight numerical policies through matched acquisition runs, compares selection from nested policy sets and scores the selected interventions on a separate archived readout. We derive an exact accounting identity for the selection contrast and examine its dependence on winner-selection scope, task, endpoint and policy family. The result is a practical reporting protocol that can be applied to different numerical screening policies, together with empirical evidence defining its behaviour in three public studies. The present experiments instantiate this framework using a shared frozen representation; its formulation does not require a particular foundation-model architecture.'''
FRAMEWORK_RESULTS='''### A paired evaluation separates acquisition from policy selection

The framework distinguishes the candidate representation, the acquisition policy and the rule that selects a reported policy (Fig. 1). Candidate features are fixed before replay. During acquisition, a policy receives only the A responses of genes already measured, and each candidate can be selected once. At the end of the trajectory, the evaluator scores exactly those genes on B. The separation is operational: changing the evaluation readout does not change the selected intervention set for a fixed trajectory. Accordingly, A and B scores describe two measurements of the same screening decision, rather than two independently optimized screens.

Policy selection is then applied to the completed trajectories. A fixed-policy comparison estimates the utility of a named policy relative to the matched random baseline. A winner-based comparison estimates the outcome of a procedure that first compares policies. Finally, the multiplicity contrast asks how much the discovery and replication gains change when the number of policies available to that procedure increases. These questions require different denominators and cannot be answered by the same headline score. Our analysis records both the selected policy and the information used to choose it, making the comparison reproducible from saved trajectories.

The paired design also specifies what counts as replication. Frangieh and Tian use separate guide partitions within their respective studies, whereas Papalexi uses separate sample labels. In all cases, B is withheld from acquisition, but its interpretation remains tied to the archive. The framework therefore evaluates transfer across specified measurements rather than assigning B the status of an error-free biological truth. This distinction is essential when interpreting both weak agreement and large apparent gains.'''
RESULTS_EXTRA={
'An exact decomposition links the contrast to policy selection':'''The decomposition can be read as a weighted comparison of existing trajectories. Policies that are selected more frequently as the choice set expands receive positive changes in weight; policies that are displaced receive negative changes. If those weight shifts favour larger A-minus-B score differences, the additional discovery gain exceeds the additional replication gain. If they favour smaller differences, the contrast reverses. Thus, the monotonic increase in the maximized A score is an algebraic consequence of nested selection, whereas the transfer contrast is an empirical property of the evaluated policy set. The identity is an accounting result, not an estimator of an unobserved biological effect or a proposed bias correction.''',
'Task-level comparisons resolve heterogeneous policy effects':'''The task-resolved display prevents two different patterns from being summarized as the same outcome. A policy can have a positive replication uplift and still show a larger discovery uplift; it can also have a small cross-readout gap because both uplifts are small. Interpreting the two panels jointly therefore matters more than ranking cells within either heatmap. The source tables retain every task-policy combination so that a study-average result can be traced to its component settings. These comparisons explain why the framework reports both utility and selection-related contrasts rather than replacing one with the other.''',
'The selection contrast persists after individual policies are omitted':'''Policy omission changes the available comparison set while preserving the underlying acquisition histories. This isolates dependence on membership of the tested family from changes caused by refitting a policy or altering the candidate pool. The analysis is consequently a check on the empirical contrast within this family, not a claim about every possible acquisition algorithm. Together with the task-resolved comparison, it gives an inspectable account of which aspects of the benchmark support the study-level summary.'''
}
DISCUSSION='''The principal result is that policy selection is part of the procedure whose efficiency must be evaluated. In this benchmark, choosing among more completed policies improved discovery hit rates more than replication hit rates in three studies, but the extent of gain transfer differed markedly. Frangieh and Tian showed large discovery improvements with relatively small replication improvements; Papalexi retained substantial gains on both measurements. Reporting the discovery score alone would obscure this distinction. Paired evaluation makes it visible by tracking the same selected interventions across readouts and by recording how the winning policy was chosen.

The contribution is a reusable evaluation design and an empirical analysis of its behaviour in sequential screening. The algebra underlying the selection contrast is elementary, but it identifies the information needed to interpret a claimed improvement: policy-specific outcomes, the selection weights and the rule that changes those weights. A result can then be examined at the level of the full decision procedure. This focus complements benchmarks of perturbation-response prediction, where the central question is how well a model predicts held-out responses [19–21]. Prediction accuracy may inform an acquisition policy, but it is not interchangeable with the utility of a sequence of chosen experiments or with the additional benefit of selecting a policy after comparison.

### Interpreting selection optimism and information leakage

The term leakage should be attached to a documented information pathway. Direct use of B responses to update an acquisition policy would violate the separation implemented here. Reusing a discovery benchmark to choose a winner and then reporting its discovery score as an independent assessment introduces a different problem: the criterion has participated in selection. Our results quantify the associated transfer contrast under specified rules; they do not infer undisclosed data use by other methods. This distinction keeps the framework applicable to legitimate adaptive screening, in which learning from previously observed A responses is the intended mechanism, while identifying when a performance claim implicitly includes an additional selection step [22,23].

A positive contrast also should not be interpreted as evidence that all discovery gains are artificial. Papalexi provides a useful example: its replication hit-rate gain was substantial despite a positive additional A–B gap. Conversely, agreement between the two gains does not establish experimental utility if both are negligible. The fixed-policy and winner-based analyses answer complementary questions, and both belong in an assessment of a sequential method. We use the difference between gains to characterize transfer, rather than labeling an entire policy successful or unsuccessful on the basis of that difference alone.

### A reporting protocol for sequential screening

A screening claim should first identify the object that was evaluated. For a policy fixed before evaluation, report the policy, its representation, the acquisition budget and the rule for updating from observed responses. For a selected winner, also report the full candidate policy set, the selection endpoint and whether selection occurred per run, per task or on a separate development partition. These details determine what information the procedure used and whether the reported trajectory could have been produced prospectively under the stated budget. Supplementary Table 9 translates these requirements into a compact reporting specification.

The next requirement is to score the same selected interventions on an explicitly defined evaluation readout. Its origin should be stated as guide partition, sample replicate, batch, donor or external study, because these provide different forms of evidence. The main endpoint, threshold calibration and any secondary endpoints should be fixed before confirmatory evaluation. If the endpoint or selection rule changes after inspection, the corresponding analysis remains useful, but it answers a secondary question. In particular, holding out random initial pools assesses stability to algorithmic initialization; it does not create new biological samples [37,38].

Comparison cost must also follow the complete procedure. Our retrospective multiplicity analysis compares several completed trajectories whose outcomes are available in the archive. A laboratory implementation could not generally obtain this information at the cost of the winning trajectory alone. Costs depend on overlap between selected genes, the reuse of measured responses and whether the candidate policies can operate on shared observations. Future evaluations should report both the nominal budget of each trajectory and the measurements or computation required to select among them. The present results concern the attribution of gains, not a demonstration of laboratory savings after all such costs have been paid.

Finally, uncertainty should correspond to the unit that was varied. The intervals reported here describe variation over matched initial pools, with related tasks averaged within each study. They quantify conditional algorithmic variability on the available archive. In a prospective study, independent experimental replicates would be needed to characterize additional biological and measurement variation. These reporting requirements connect the sequential setting to broader concerns in biomedical machine learning and to established guidance on reproducibility and model evaluation [23,34–36]. They are intended as an operational protocol for subsequent studies, rather than an already validated community standard.

### Biological readouts and representation choice

Readout agreement helps describe why selection gains transfer differently, but is not isolated experimentally in this comparison. The studies also differ in candidate-pool size, guide structure, cellular context and budget. It would therefore be premature to assign the between-study contrast to rank agreement alone. The framework makes these design features explicit so that later experiments can vary them separately. The source studies establish the cancer-immune, immune-regulatory and neuronal contexts [24–26]; here, the transcriptional programmes define evaluation endpoints. In Tian, immune-related programmes serve as a response-based stress test and do not constitute a new claim about neuronal disease mechanisms.

The continuous-score reversal in Papalexi is particularly informative. Thresholded hit rate and a scaled continuous response emphasize different features of the outcome distribution, and the sensitivity analysis changes both the criterion used to choose the winner and the metric used to evaluate it. The reversal therefore cannot be attributed solely to threshold removal. It demonstrates that the endpoint and selection operation must be specified jointly. A policy-selection result is transferable only relative to a defined target of evaluation, not as a context-free property of a model.

Foundation models introduce another choice that belongs inside the evaluation design. Geneformer, scGPT and scFoundation provide different representations and use modes [13–15]. Recent evaluations show that downstream utility depends on the task, the extraction procedure and pretraining choices [27–29]. A pretrained gene-token vector, a contextual gene representation and a whole-cell embedding are different inputs to a screening policy. Our principal comparison fixes static Geneformer input vectors and the same projection across policies so that differences in acquisition and selection can be examined directly. This is not a benchmark of the full contextual transformer or a numerical comparison of the published foundation-model systems.

A representation extension should therefore preserve candidate identities, response definitions, budgets and initial pools while replacing only the feature map and its prespecified preprocessing. Feature normalization or dimensionality reduction must be fitted on an allowed development set, and missing vocabulary entries must be reported before outcomes are compared. Cell-level embeddings require a further design decision: aggregating post-perturbation measurements to represent an unmeasured candidate could expose information that a prospective acquisition policy would not possess. Reference mapping, atlas integration and probabilistic modelling offer useful tools for defining permissible context, but do not remove this information constraint [30–33]. Supplementary Methods 5 specifies how the paired framework can accommodate such controlled representation comparisons.

### Scope and next evaluation steps

The main multiplicity analysis was developed after external outcomes were available. Its consistency across the tested hit-rate settings supports a focused hypothesis about selection-related gains, while the selection-scope and continuous-endpoint results delimit that hypothesis. Independent confirmation should specify the policy family, selection rule, endpoint and replication design before observing the evaluation outcomes. The framework provides those operational definitions and the trajectories needed to audit the current results; it does not convert exploratory analysis into prospective confirmation.

Paired evaluation offers a practical way to assess progress in sequential screening. It preserves the distinction between a policy that chooses useful interventions and a procedure that chooses an impressive-looking policy after comparison. By reporting both processes, subsequent studies can establish whether an improvement survives policy selection, transfers to the intended readout and remains meaningful after the cost of comparison is included. This makes the claimed gain easier to reproduce and connects computational performance to a clearly defined experimental decision.'''
METHODS_ADD='''### Evaluation target and information available to the procedure

Each archived task defines a fixed set of candidate interventions with features and two response measurements. The acquisition history contains the identities of selected candidates and their observed A responses. An acquisition policy maps that history to an unmeasured batch. It does not receive unqueried A responses or any B responses. The evaluator has access to complete archived responses and computes terminal scores after the policy has stopped. This separation is enforced by the numerical implementation and checked from the saved trajectories; it is not a claim of adversarial software isolation.

We distinguish policy acquisition from the meta-level selection of a reported policy. The latter operates on completed runs and can use their A scores under the specified selection rule. For a fixed trajectory, B is always scored on the same candidate identities selected through A. For an endpoint sensitivity analysis that reselects the winning policy, the selected trajectory can change, but its A and B evaluations remain paired. These definitions specify the estimand and prevent the interpretation of a winner-based score as the performance of a policy fixed before comparison.

### Scope of the proposed reporting protocol

Supplementary Table 9 records the information required to reproduce a sequential-screening comparison: source data and partitions, feature provenance, candidate eligibility, initial pools, acquisition budgets, the candidate policy family, the selection endpoint, comparison costs and the uncertainty unit. This table is a proposed reporting protocol derived from the evaluation design; compliance with it is not itself evidence that a method improves biological outcomes. Numerical results are reported separately from design recommendations. Comparisons that introduce new representations or revise the winner-selection rule are labeled as additional analyses and do not modify the archived primary trajectories.'''
SI_METHODS='''Supplementary Methods 5 Controlled extensions to pretrained representations

A controlled representation comparison replaces the candidate feature map while preserving the archived response arrays, task definitions and matched acquisition design. The model name, checkpoint identifier, extraction layer and gene vocabulary must be recorded. Static token embeddings can be attached to a candidate gene before its response is measured. Contextual representations instead require the cell or gene-expression context used at inference to be specified, including whether that context would be available before acquisition.

Fit feature scaling and any projection using a separate, permitted development feature set. Keep the target dimensionality and acquisition hyperparameters fixed when the purpose is to isolate representation choice. Report candidate coverage for each model. If candidates are removed because of vocabulary mismatch, rerun every comparator on the identical intersection and report the change from the original pool; such a comparison is not directly interchangeable with the full-pool benchmark. Do not fill missing pretrained vectors using target responses.

Run the replacement policy with the original initial-pool seeds and evaluate its selected genes on both A and B. Compare paired seed-level outcomes after averaging related tasks within each study. A supplementary example with one representation and one policy tests a particular use mode; it does not establish state-of-the-art performance of the complete foundation model or validate the framework across all representations. Extending the model family after inspection of existing outcomes should be recorded in the analysis chronology.'''
